FROM ubuntu:12.04
MAINTAINER Jonathan Calazan "jonathan@calazan.com

RUN apt-get -y update && apt-get install -y \
    build-essential \
    curl \
    git \
    libpq-dev \
    sudo \
    vim \
    python-dev \
    python-pip \
    python-pycurl \
    python-software-properties