FROM ubuntu:12.04
MAINTAINER Jonathan Calazan "jonathan@calazan.com"

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    python-dev \
    python-pip \
    python-pycurl \
    python-software-properties \
    sudo \
    vim